# Generated by Django 5.0.7 on 2024-07-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0003_alter_message_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='address',
            field=models.CharField(default='ToGod', max_length=30),
        ),
    ]
