# Generated by Django 5.0.7 on 2024-07-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0005_order_profile_urlsorders_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='sent', max_length=15),
        ),
    ]
