# Generated by Django 5.0.7 on 2024-07-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsorders',
            name='url_isCloud',
            field=models.BooleanField(default=False),
        ),
    ]
