# Generated by Django 5.0.7 on 2024-08-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0009_group_alter_order_created_time_alter_order_deadline_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='UserGroup',
        ),
    ]
