# Generated by Django 5.0.7 on 2024-08-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0010_rename_group_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='privilege_level',
            field=models.IntegerField(default=0),
        ),
    ]
