# Generated by Django 5.0.7 on 2024-08-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0012_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='aftereffects',
            new_name='sk_aftereffects',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='audition',
            new_name='sk_audition',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='photoshop',
            new_name='sk_photoshop',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='cut',
            new_name='sk_prempro',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='effects',
            new_name='sk_subtitles',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='illustrator',
            new_name='sk_transitions',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='infograf',
            new_name='sk_vegaspro',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='memes',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='prempro',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='subtitles',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='transitions',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='vegaspro',
        ),
        migrations.AddField(
            model_name='skills',
            name='sk_cut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skills',
            name='sk_effects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skills',
            name='sk_illustrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skills',
            name='sk_infograf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skills',
            name='sk_memes',
            field=models.BooleanField(default=False),
        ),
    ]
